FROM sonarqube:lts

RUN wget https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/releases/download/1.1.4/sonar-dependency-check-plugin-1.1.4.jar -P /opt/sonarqube/extensions/plugins
